import type { Metadata } from "next";
import "./../styles/globals.css";


export const metadata: Metadata = {
  title: "3d website",
  description: "Generated by sadisu",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
      <body>{children}</body>
    </html>
  );
}
